name: Codegen Dry Run

on:

  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository 🛎️
        uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: https://registry.npmjs.org/

      - name: Code Generation
        run: |
          git submodule update --remote
          CHANGES_DESC="build-$(date +%Y%m%d-%H%M%S)"
          yarn
          yarn codegen
          git add .
          if ! git diff --staged --quiet; then
            echo "build 🛠 $CHANGES_DESC"
            echo "GIT_RESULT=Changes detected." >> $GITHUB_ENV
          else
            echo "GIT_RESULT=No changes to commit." >> $GITHUB_ENV
          fi
      - name: Git Changes Result
        run: |
          echo $GIT_RESULT
