name: Publish Min Test

on:
  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"
      - uses: actions/setup-node@v3
        with:
          node-version: 16.14.0
          registry-url: https://registry.npmjs.org/
      - name: Code Generation
        run: |
          BRANCH_NAME="build-$(date +%Y%m%d-%H%M%S)"
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"
          git checkout -b $BRANCH_NAME
          cd packages/chain-registry
          echo a > test.ts
          echo "console.log('Example finished');" >> examples/examples.ts
          cd ../../
          git add .
          if ! git diff --staged --quiet; then
            git commit -am "build 🛠 $BRANCH_NAME"
            git push --set-upstream origin $BRANCH_NAME
            echo "GIT_RESULT=Created" >> $GITHUB_ENV
          else
            echo "GIT_RESULT=No changes to commit." >> $GITHUB_ENV
          fi
      - name: Git Ops
        run: |
          echo $GIT_RESULT
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_SECRET}}
          GH_TOKEN: ${{ secrets.GH_LERNA_PUBLISH_TOKEN }}
